# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestYyy():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_yyy(self):
    self.driver.get("https://10.30.33.25/")
    self.driver.set_window_size(946, 697)
    self.driver.find_element(By.ID, "login_user").click()
    self.driver.find_element(By.ID, "login_user").send_keys("system")
    self.driver.find_element(By.ID, "login_user").send_keys(Keys.ENTER)
    self.driver.find_element(By.XPATH, "//div[@id=\'navBar_item_计算_content\']/span").click()
    self.driver.find_element(By.XPATH, "//li[@id=\'navBar_item_计算_content_云服务器\']/span").click()
    self.driver.find_element(By.XPATH, "//li/ul/li[2]/div/span").click()
    self.driver.find_element(By.XPATH, "//li[2]/ul/li/div/span").click()
    self.driver.find_element(By.XPATH, "//li[2]/ul/li/ul/li/div/span").click()
    self.driver.find_element(By.XPATH, "//li[2]/ul/li/ul/li/ul/li/div/div/div/div").click()
    element = self.driver.find_element(By.ID, "compute_virtual_refreshBtn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.close()
  
